Repository icecube/skyllh, pull requests merged in 2022-05, with the labels that each got.

#102 add function to compute pval from gamma-fit to trials ...
  skyllh/core/analysis_utils.py
Labels: enhancement

#104 Fix `mu_fluxes` indexing in `mu2flux` method
  skyllh/core/signal_generator.py
Labels: bug

#103 Add multiversion support to sphinx documentation generation
  .github/workflows/documentation.yml
  doc/sphinx/Makefile
  doc/sphinx/_assets/gh-pages-redirect.html
  doc/sphinx/_templates/versions.html
  doc/sphinx/conf.py
  doc/sphinx/requirements.txt
Labels: documentation
